### ISSUE TITLE
panic on hello world

### ISSUE THREAD

**Issue by terinjokes** [NateGraff/blessedvirginmary#1]
When I attempt to run over hello.ll, I get the following output:

```bash
main() {
declare -A local
eval `_brmain0 local[@]`
ret=${local[ret]}
declare -p ret
}
_brmain0() {
local=${!1}
eval `printf`
local[r1]=${ret}
local[ret]=0
declare -p local
}
printf() {
declare -A local
panic: runtime error: index out of range

goroutine 1 [running]:
main.convertFuncToBash(0xc420132120)
        /home/terin/go/src/github.com/NateGraff/blessedvirginmary/bvm.go:197 +0x441
main.main()
        /home/terin/go/src/github.com/NateGraff/blessedvirginmary/bvm.go:226 +0x8c
```

It seems the printf function has no generated IR:

```ir
@.str = private unnamed_addr constant [13 x i8] c"Hello world\0A\00", align 1

; Function Attrs: noinline nounwind optnone sspstrong uwtable
define i32 @main() #0 {
  %1 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([13 x i8], [13 x i8]* @.str, i32 0, i32 0))
  ret i32 0
}

declare i32 @printf(i8*, ...) #1
```

```console
$ clang --version
clang version 6.0.1 (tags/RELEASE_601/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by NateGraff** [comment]
Hi Terin! Thanks for looking at our project!

Yeah, we don’t have hello working yet. The plan if we ever continue development is to get function parameters working and then start work on a standard library and linker.
